In [1]:
import numpy as np

Creating array of 10 zeros

In [2]:
zero=np.zeros(10)
print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Creating array of 10 ones

In [3]:
ones=np.ones(10)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Creating array of 10 fives

In [7]:
fives=np.ones(10)*5
print(fives)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Creating array of integers from 10 to 50

In [11]:
arr=np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


Creating array of even integers from 10 to 50

In [12]:
array=np.arange(10,51,2)
print(array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


Creating 3X3 matrix ranging from 0 to 8

In [15]:
mat=np.arange(0,9).reshape(3, 3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Creating the 3X3 identity matrix

In [16]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Use numpy to generate random number between 0 and 1

In [17]:
from numpy import random

In [20]:
x=random.rand(1)
print(x)

[0.10527831]


Use numpy to generate an array of 25 random numbers sampled from a standard normal distribution

In [21]:
b=np.random.normal(0,1,25)
print(b)

[-3.23159501e-01 -5.56071343e-01  4.68545057e-01 -1.52445307e+00
 -9.16103605e-01 -2.44940909e+00  6.65216031e-01 -2.43009460e-01
 -7.89837231e-01  2.22956326e+00  1.22619192e+00 -2.07927650e-01
  2.23054668e-01 -5.74712622e-01 -7.86741232e-05  2.16986933e+00
 -7.24450735e-01 -3.34205698e-01 -1.50851791e+00 -3.52459904e-01
  2.77037351e-01  1.73897766e+00 -5.04322801e-01 -8.08259532e-01
  4.23682934e-02]


Printing the following

In [25]:
c=np.arange(0,1.01,0.01)
print(c)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]


In [26]:
matrix=np.arange(1,26).reshape(5,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])